# Generated by Django 3.2.9 on 2021-12-01 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppSpa', '0006_alter_tag_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='slug',
        ),
    ]
