# Generated by Django 3.2.9 on 2021-12-01 20:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('AppSpa', '0008_tag_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(default=uuid.uuid1, unique=True),
        ),
    ]
