# Generated by Django 3.2.9 on 2021-12-01 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppSpa', '0009_alter_tag_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
