# Generated by Django 3.2.9 on 2021-12-01 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppSpa', '0010_alter_tag_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='slug',
            new_name='slug_tag',
        ),
    ]
