# Generated by Django 3.2.9 on 2021-12-01 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppSpa', '0011_rename_slug_tag_slug_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='slug_tag',
            new_name='slugTag',
        ),
    ]
