# Generated by Django 3.2.9 on 2021-12-01 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppSpa', '0012_rename_slug_tag_tag_slugtag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='slugTag',
            new_name='slug',
        ),
    ]
